<?php
/** @var \Inchoo\ProductFAQ\Block\Customer\ListCustomer $block */
?>
<?php if ($questions = $block->getQuestions()) : ?>
    <div class="page-wrapper faq">
        <?php foreach ($block->getQuestions()->getData() as $question) : ?>
        <div class="title-row">
            <h4 class="title">
                Question regarding product
                <span data-content="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col product-name">
                    <a href="<?= $block->escapeUrl($block->getProductUrl($question['product_id'])) ?>">
                        <?= $block->escapeHtml($question['productName']) ?>
                    </a>
                </span>
            </h4>
            <p data-content="<?= $block->escapeHtmlAttr(__('Created')) ?>" class="col date">
                Created At: <small><?= $block->escapeHtml($block->dateFormat($question['created_at'])) ?></small>
            </p>
            <p data-content="<?= $block->escapeHtmlAttr(__('Question')) ?>" class="col question-content">
                <strong class="faq-question">
                   Q: <?= $block->escapeHtml($question['question_content']) ?>
                </strong>
            </p>
            <p data-content="<?= $block->escapeHtmlAttr(__('Answer')) ?>" class="col actions">
                <i><?= $question['answer_content'] ? '<strong>A:</strong> ' . $block->escapeHtml($question['answer_content']) : 'No answer yet.' ?></i>
            </p>
            <hr>
        </div>
        <?php endforeach ?>
    </div>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have submitted no questions.')) ?></span></div>
<?php endif ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
